[cosmic-ray]
module-path = "src"
timeout = 30.0
excluded-modules = []
test-command = "pytest"

[cosmic-ray.distributor]
name = "local"

[cosmic-ray.badge]
label = "🧬 killed mutants"
format = "%.2f %%"

[cosmic-ray.badge.thresholds]
50  = "red"
70  = "yellow"
90 = "green"