[build-system]
requires = ["setuptools>=64.0"]
build-backend = "setuptools.build_meta"

[project]
name = "test_cosmic_ray"
version = "0.1.0"
requires-python = ">=3.13"

dependencies = [
    "pytest==8.3.*",
    "cosmic-ray==8.4.*",
]