name: Mutation test
run-name: Testing Mutated Code

on:
  workflow_dispatch:

jobs:
  mutation-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PUSH_KILLED_MUTANTS_BADGE_TOKEN }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install dependencies
        run: uv sync --all-extras --frozen

      - name: Run tests
        run: |
          uv run cosmic-ray init \
            --force \
            ./.cosmic-ray-config.toml \
            ./.cosmic-ray-session.sqlite
          uv run cosmic-ray exec \
            ./.cosmic-ray-config.toml \
            ./.cosmic-ray-session.sqlite
          uv run cr-badge \
            ./.cosmic-ray-config.toml \
            ./assets/killed_mutants_badge.svg \
            ./.cosmic-ray-session.sqlite
          uv run cr-html \
            --skip-success \
            ./.cosmic-ray-session.sqlite > survived_mutants.html

      - name: Upload new badge
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add ./assets/killed_mutants_badge.svg
          git commit -m "Update killed mutants badge" \
            || echo "No changes in 'killed_mutants_badge.svg' file"
          git push

      - name: Upload survived mutants report
        uses: actions/upload-artifact@v4
        with:
          name: survivors-mutants-report
          path: survived_mutants.html